from pathlib import Path
import pandas as pd, matplotlib.pyplot as plt
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle, PageBreak
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
ROOT=Path(__file__).resolve().parents[1]; D=ROOT/'data'/'processed'; F=ROOT/'outputs'/'figures'; F.mkdir(parents=True,exist_ok=True)
f=pd.read_csv(D/'financial_quarterly.csv'); cf=pd.read_csv(D/'cashflow_quarterly.csv'); cap=pd.read_csv(D/'capex_quarterly.csv'); wc=pd.read_csv(D/'working_capital_quarterly.csv'); debt=pd.read_csv(D/'debt_quarterly.csv'); cpv=pd.read_csv(D/'cpv_quarterly.csv'); periods=['1T25','2T25','3T25','4T25','1T26','2T26']; x=f[f.period.isin(periods)].copy()
for y in [cf,cap,wc]: x=x.merge(y,on='period',how='left')
# charts
plt.figure(); plt.plot(x.period,x.revenue/1000,marker='o',label='Receita'); plt.plot(x.period,x.ebitda/1000,marker='o',label='EBITDA'); plt.ylabel('R$ milhões'); plt.title('Receita líquida e EBITDA'); plt.legend(); plt.tight_layout(); plt.savefig(F/'01_receita_ebitda.png',dpi=160); plt.close()
plt.figure(); plt.plot(x.period,x.gross_margin*100,marker='o',label='Margem bruta'); plt.plot(x.period,x.ebitda_margin*100,marker='o',label='Margem EBITDA'); plt.plot(x.period,x.net_margin*100,marker='o',label='Margem líquida'); plt.ylabel('%'); plt.title('Margens'); plt.legend(); plt.tight_layout(); plt.savefig(F/'02_margens.png',dpi=160); plt.close()
plt.figure(); plt.bar(x.period,x.operating_cash_flow/1000,label='FCO'); plt.plot(x.period,x.capex_mn,marker='o',label='CAPEX'); plt.ylabel('R$ milhões'); plt.title('Fluxo de caixa operacional e CAPEX'); plt.legend(); plt.tight_layout(); plt.savefig(F/'03_caixa_capex.png',dpi=160); plt.close()
components=['Carvão e coque','Energia e Combustíveis','Mão de Obra Total','Minérios']; cpv=cpv[cpv.cost_component.isin(components)]; cp=cpv[cpv.period.isin(periods)].pivot_table(index='period',columns='cost_component',values='share',aggfunc='last'); plt.figure(figsize=(8,4.5)); cp.plot.area(ax=plt.gca()); plt.ylabel('Participação'); plt.title('Composição do CPV'); plt.legend(loc='center left',bbox_to_anchor=(1,0.5)); plt.tight_layout(); plt.savefig(F/'04_cpv.png',dpi=160); plt.close()
# findings
r3=x.iloc[2]; r4=x.iloc[3]; r6=x.iloc[-1]; debt['date']=pd.to_datetime(debt.date); d25=debt[debt.date>=pd.Timestamp('2025-01-01')].copy(); nd_start=d25.iloc[0].net_debt/1000; nd_end=d25.iloc[-1].net_debt/1000
x_corr=x.merge(cp.reset_index(),on='period',how='left'); corr=x_corr[['ebitda_margin','revenue','operating_cash_flow','capex_mn','working_capital_bn','Carvão e coque','Energia e Combustíveis','Mão de Obra Total','Minérios']].corr()['ebitda_margin'].sort_values(ascending=False)
styles=getSampleStyleSheet(); doc=SimpleDocTemplate(str(ROOT/'reports'/'relatorio_usiminas.pdf'),pagesize=A4,rightMargin=40,leftMargin=40,topMargin=40,bottomMargin=40); story=[]
story += [Paragraph('Usiminas — Recuperação operacional e financeira entre 2025 e 2026',styles['Title']),Paragraph('Projeto exploratório de análise de dados baseado na planilha Base de Dados para Modelagem 2T26.',styles['Normal']),Spacer(1,12)]
story += [Paragraph('1. Pergunta de pesquisa',styles['Heading2']),Paragraph('Quais fatores operacionais e financeiros acompanharam a recuperação da rentabilidade da Usiminas entre o 3T25 e o 2T26?',styles['BodyText'])]
story += [Paragraph('2. Metodologia',styles['Heading2']),Paragraph('Foram extraídas e normalizadas séries trimestrais de DRE, fluxo de caixa, CAPEX, capital de giro, dívida e composição do CPV. A análise concentra-se em 1T25–2T26 para contextualizar a ruptura do 3T25 e a recuperação subsequente. Os valores são apresentados em R$ milhões ou bilhões apenas para leitura. A análise é descritiva; correlação não implica causalidade.',styles['BodyText'])]
story += [Paragraph('3. Resultados',styles['Heading2']),Image(str(F/'01_receita_ebitda.png'),width=500,height=280),Paragraph(f'No 3T25, o EBITDA foi de R$ {r3.ebitda/1000:,.0f} mi, com margem de {r3.ebitda_margin:.1%}. No 4T25, voltou para R$ {r4.ebitda/1000:,.0f} mi e margem de {r4.ebitda_margin:.1%}. No 2T26, alcançou R$ {r6.ebitda/1000:,.0f} mi e margem de {r6.ebitda_margin:.1%}.',styles['BodyText']),Spacer(1,8),Image(str(F/'02_margens.png'),width=500,height=280)]
story += [Paragraph('4. Caixa, investimento e capital de giro',styles['Heading2']),Image(str(F/'03_caixa_capex.png'),width=500,height=280),Paragraph(f'O fluxo de caixa operacional foi de R$ {r6.operating_cash_flow/1000:,.0f} mi no 2T26, contra R$ {r3.operating_cash_flow/1000:,.0f} mi no 3T25. O CAPEX do 2T26 foi de R$ {r6.capex_mn:,.0f} mi. O capital de giro terminou o trimestre em R$ {r6.working_capital_bn:,.2f} bi.',styles['BodyText'])]
story += [Paragraph('5. Estrutura de custos',styles['Heading2']),Image(str(F/'04_cpv.png'),width=500,height=280),Paragraph('A composição do CPV mostra peso relevante de matérias-primas, carvão/coque, mão de obra, energia e minérios. A recuperação de margem deve ser interpretada conjuntamente com volume, preços, mix e custos; a base não permite atribuir causalidade isolada a um único componente.',styles['BodyText'])]
story += [Paragraph('6. Endividamento',styles['Heading2']),Paragraph(f'A dívida líquida caiu de aproximadamente R$ {nd_start:,.0f} mi no início de 2025 para R$ {nd_end:,.0f} mi no 2T26, passando inclusive para saldo líquido negativo no fechamento mais recente. Isso reforça a leitura de melhora da posição financeira, embora dívida líquida não seja uma medida de rentabilidade operacional.',styles['BodyText'])]
story += [Paragraph('7. Correlações exploratórias',styles['Heading2']),Paragraph('Na janela de seis trimestres, algumas associações com a margem EBITDA são: '+ '; '.join([f'{k}: {v:.2f}' for k,v in corr.items() if k!='ebitda_margin'])+'. A amostra é pequena e não deve sustentar inferências causais.',styles['BodyText'])]
story += [Paragraph('8. Conclusão',styles['Heading2']),Paragraph('Os dados sustentam uma narrativa de recuperação: após o choque do 3T25, EBITDA, margem EBITDA e geração operacional de caixa melhoraram nos trimestres seguintes. Ao mesmo tempo, capital de giro permaneceu em patamar inferior ao observado no início de 2025 e a dívida líquida recuou. A explicação completa, porém, exige decomposição adicional de preço, volume, mix e custos.',styles['BodyText'])]
story += [Paragraph('9. Limitações e próximos passos',styles['Heading2']),Paragraph('A análise não incorpora preços de aço de mercado, câmbio externo, indicadores macroeconômicos ou eventos extraordinários fora da base. Próximos passos: testar regressões simples com maior histórico, decompor volume/preço/mix, comparar Usiminas com pares e investigar separadamente o 3T25.',styles['BodyText'])]
doc.build(story)
print(ROOT/'reports/relatorio_usiminas.pdf')
